from setuptools import setup, find_packages

setup(
    name="imac_scorecard",
    version="0.1.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "pandas",
        "numpy",
        "scikit-learn",
        "statsmodels",
        "shap",
        "matplotlib",
        "seaborn",
    ],
    extras_require={
        'dev': [
            'pytest>=6.0',
            'pytest-cov>=2.0',
            'black>=22.0',
            'flake8>=3.9',
            'mypy>=0.9',
        ],
        'docs': [
            'sphinx>=4.0',
            'sphinx-rtd-theme>=1.0',
            'nbsphinx>=0.8',
            'jupyter>=1.0',
        ],
    },
    python_requires=">=3.6",
    author="Your Name",
    author_email="your.email@example.com",
    description="IMAC Scorecard Implementation",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/imac_scorecard",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "Intended Audience :: Financial and Insurance Industry",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Office/Business :: Financial :: Investment",
    ],
    keywords="credit scoring, risk assessment, machine learning, financial analysis",
    project_urls={
        "Bug Reports": "https://github.com/yourusername/imac_scorecard/issues",
        "Source": "https://github.com/yourusername/imac_scorecard",
        "Documentation": "https://imac-scorecard.readthedocs.io/",
    },
) 